### ISSUE TITLE
rodps.init()报错

### ISSUE THREAD

**Issue by GOUYONGCHAO** [aliyun/aliyun-odps-r-plugin#10]
请教大神

我用rodps.init("配置文件地址")报错
```
rodps.init("c\\users\\xxx\\R\\odps_config.ini“)
```
报错结果：
```
Error in strsplit(row,"")：non-character argument
```
配置文件内容如下：

> access_id= xxx
> access_key= xxx
> end_point= xxx
> tunnel_endpoint= xxx 
> project_name=  sit_bdp_adm

配置文件加引号也不行
而且xxx和=之间必须加空格，不加空格也会报错，这些key和网址需要加引号部？

请教大神，这种情况怎么处理？

我用Linux Server版的R也出这个问题。
[报错截图](https://www.jianshu.com/p/a2e9ae05aecf)

**Comment by lyman** [comment]
不需要加引号，也不需要加空格

`rodps.init("c\\users\\xxx\\R\\odps_config.ini“)` 这个路径的写法看着不对啊，windows 下直接 `c:\users\...` 这样些应该就可以了
