### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by LeslieTsui** [aliyun/aliyun-odps-r-plugin#13]
*** arch - i386
Warning: package 'rJava' was built under R version 3.5.3
Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error : package 'rJava' could not be loaded
错误: 载入失败
停止执行
*** arch - x64
Warning: package 'rJava' was built under R version 3.5.3
Warning: package 'DBI' was built under R version 3.5.3
Warning: package 'RSQLite' was built under R version 3.5.3
checking RODPS_CONFIG ...
checking ODPS_CONFIG ...
checking C:/Users/xulei/Documents/odps_config.ini ...
checking C:/Users/xulei/Documents/.odpscmd/odps_config.ini ...
RODPS_CONFIG environment variable is not set or the configuration file does not exist.
- rodps.init(path) to manually init RODPS
- add RODPS_CONFIG as environment variable
ERROR: loading failed for 'i386'
* removing 'C:/Users/xulei/Documents/R/R-3.5.1/library/RODPS'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/xulei/AppData/Local/Temp/RtmpobjU8O/downloaded_packages/RODPS_2.0.2.tar.gz’ had non-zero exit status

**Comment by LeslieTsui** [comment]
这是系统版本信息
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray

**Comment by lyman** [comment]
rJava 都没装成功啊

系统，R，Java，都装成一样字长比较好，现在基本上都是 64 位的。包括 R，安装的时候不要 32+64 两个都勾选

**Comment by hanshanzgy** [comment]
这个问题解决了没？我也碰到相同过得错误。
