### ISSUE TITLE
执行 sql 一直在报错

### ISSUE THREAD

**Issue by lwenxu** [aliyun/aliyun-odps-r-plugin#15]
执行下的 sql：
rodps.sql("SELECT  *
FROM    xx.xx
WHERE   ds = MAX_PT('xx.xx')")

![image](https://user-images.githubusercontent.com/22151420/83378551-9636f100-a40b-11ea-8d20-fc6ed4018e12.png)

**Comment by lyman** [comment]
endpoint 配置的有问题
