### ISSUE TITLE
R本地安装RODPS报错

### ISSUE THREAD

**Issue by wangdalong93** [aliyun/aliyun-odps-r-plugin#19]
命令：install.packages('rodps',repos='http://odps.alibaba-inc.com/rodps')
报错信息：
Warning in install.packages :
  unable to access index for repository http://odps.alibaba-inc.com/rodps/src/contrib:
  Line starting '<!DOCTYPE html> ...' is malformed!
Warning in install.packages :
  package ‘rodps’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  unable to access index for repository http://odps.alibaba-inc.com/rodps/bin/macosx/big-sur-arm64/contrib/4.2:
  Line starting '<!DOCTYPE html> ...' is malformed!

**Comment by caesar0301** [comment]
@wangdalong93 We are not maintaining the old `rodps` repo. Please refer to README for latest installation. Or download package from Github releases and install offline with `R CMD INSTALL <path-to-package.tar.gz>`
