### ISSUE TITLE
rodps.table.read私有云文件时候报错

### ISSUE THREAD

**Issue by GOUYONGCHAO** [aliyun/aliyun-odps-r-plugin#9]
我在读取私有云文件的时候报错，不知道怎么解决。
我用下面两个语句都会报错：
x<-rodps.table.read('ods_zhxya')
x<-rodps.table.read('ods_zhxya',partition =****,limit=-1,isdebug=TRUE) 
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  com.aliyun.odps.rodps.DataTunnel.ROdpsException: MissingPartitionSpecYou need to specify a partitionspec along with the specified table.

**Comment by lyman** [comment]
读取的是个分区表，用 rodps.table.read 的时候要加上分区描述。partition 怎么写参考官方文档 https://help.aliyun.com/document_detail/27820.html

如果你需要读全部分区，rodps.table.read 是不支持的，需要改用 rodps.sql("select ... from table") 这样
